const daysAgo = (n) => { 
  const d = new Date(); 
  d.setDate(d.getDate() - n); 
  return d.toISOString().slice(0, 10); 
};

export const DUMMY_TEAM = [
  { id: 'u1', name: 'Umer', role: 'Full-Stack Developer', email: 'umer@cashtrack.com', password: 'umer123', avatarColor: 'from-blue-400 to-indigo-500' },
  { id: 'u2', name: 'Laiba', role: 'UI/UX Designer', email: 'laiba@cashtrack.com', password: 'laiba123', avatarColor: 'from-pink-400 to-rose-500' },
];

export const DUMMY_CLIENTS = [
  { id: 'c1', name: 'Fiverr Client', company: 'US Startup — Nova Labs', email: 'alex@novalabs.io', avatarColor: 'from-emerald-400 to-teal-500' },
  { id: 'c2', name: 'Local Shop Owner', company: 'Al-Madina Stores, Karachi', email: 'shop.almadina@gmail.com', avatarColor: 'from-amber-400 to-orange-500' },
  { id: 'c3', name: 'Sarah Mitchell', company: 'Upwork — Freelance', email: 'sarah.m@outlook.com', avatarColor: 'from-violet-400 to-fuchsia-500' },
  { id: 'c4', name: 'DesignPro Agency', company: 'DesignPro (Pvt) Ltd', email: 'projects@designpro.pk', avatarColor: 'from-sky-400 to-blue-500' },
  { id: 'c5', name: 'Ali Raza', company: 'Friend Referral', email: 'ali.raza@yahoo.com', avatarColor: 'from-rose-400 to-pink-500' },
];

export const DUMMY_TRANSACTIONS = [
  { id: 't1', type: 'income', amount: 450, currency: 'USD', clientId: 'c1', assigneeId: 'u1', category: 'Development', date: daysAgo(2), description: 'Landing page build', status: 'paid', isAutoGenerated: true, linkedInvoiceId: 'inv1' },
  { id: 't3', type: 'expense', amount: 29, currency: 'USD', clientId: null, assigneeId: null, category: 'Subscription', date: daysAgo(7), description: 'Figma Professional plan', status: 'paid' },
];

export const DUMMY_TASKS = [
  { id: 'tk1', title: 'Design Homepage UI', description: 'Create high-fidelity mockups.', clientId: 'c1', assigneeId: 'u2', status: 'completed', compensation: 150, currency: 'USD', dueDate: daysAgo(2), createdAt: daysAgo(10) },
  { id: 'tk2', title: 'Integrate Stripe API', description: 'Set up payment intents.', clientId: 'c3', assigneeId: 'u1', status: 'in-progress', compensation: 200, currency: 'USD', dueDate: daysAgo(-2), createdAt: daysAgo(5) },
  { id: 'tk3', title: 'Login Page', description: 'Build secure login form.', clientId: 'c4', assigneeId: 'u1', status: 'pending', compensation: 25, currency: 'USD', dueDate: daysAgo(-5), createdAt: daysAgo(3) },
];

export const DUMMY_INVOICES = [
  { 
    id: 'inv1', invoiceNumber: 'INV-001', clientId: 'c1', createdBy: 'admin',
    items: [{ description: 'Landing Page Design & Development', amount: 450, taskId: 'tk_dummy' }], 
    status: 'paid', issueDate: daysAgo(10), dueDate: daysAgo(0), total: 450, currency: 'USD' 
  },
];