import { useState, useEffect, useCallback, useMemo } from 'react';
import { supabase } from '../lib/supabase';
import { convertAmount } from '../lib/currency';
import { useAuth } from '../context/AuthContext';

export const useCashTrack = () => {
  const { user } = useAuth();
  const [data, setData] = useState({
    clients: [], profiles: [], tasks: [], invoices: [], transactions: [], payouts: []
  });
  const [loading, setLoading] = useState(true);
  const [displayCurrency, setDisplayCurrency] = useState('USD');
  const [theme, setTheme] = useState(() => localStorage.getItem('cashtrack_theme') || 'dark');

  // Apply theme to HTML tag
  useEffect(() => {
    const root = window.document.documentElement;
    root.classList.remove('light', 'dark', 'midnight', 'ocean');
    root.classList.add(theme);
    localStorage.setItem('cashtrack_theme', theme);
  }, [theme]);

  const fetchData = useCallback(async () => {
    if (!user) { setLoading(false); return; }
    setLoading(true);
    
    try {
      const [
        { data: clients }, { data: profiles }, { data: tasks },
        { data: invoices }, { data: transactions }, { data: payouts }
      ] = await Promise.all([
        supabase.from('clients').select('*').order('created_at', { ascending: false }),
        supabase.from('profiles').select('*').order('created_at', { ascending: false }),
        supabase.from('tasks').select('*').order('created_at', { ascending: false }),
        supabase.from('invoices').select('*').order('created_at', { ascending: false }),
        supabase.from('transactions').select('*').order('created_at', { ascending: false }),
        supabase.from('payouts').select('*').order('created_at', { ascending: false })
      ]);

      const normalize = (arr, mapFn) => arr ? arr.map(mapFn) : [];

      setData({
        clients: normalize(clients, c => ({ ...c, avatarColor: c.avatar_color })),
        profiles: normalize(profiles, p => ({ ...p, avatarColor: p.avatar_color })),
        tasks: normalize(tasks, t => ({
          ...t, clientId: t.client_id, assigneeId: t.assignee_id,
          dueDate: t.due_date, completedAt: t.completed_at, createdAt: t.created_at
        })),
        invoices: normalize(invoices, i => ({
          ...i, clientId: i.client_id, createdBy: i.created_by,
          issueDate: i.issue_date, dueDate: i.due_date,
          linkedTaskIds: i.linked_task_ids || []
        })),
        transactions: normalize(transactions, t => ({
          ...t, clientId: t.client_id, assigneeId: t.assignee_id,
          isAutoGenerated: t.is_auto_generated, linkedInvoiceId: t.linked_invoice_id
        })),
        payouts: normalize(payouts, p => ({
          ...p, memberId: p.member_id, taskId: p.task_id,
          invoiceId: p.invoice_id, invoiceNumber: p.invoice_number
        }))
      });
    } catch (error) {
      console.error('Data fetch error:', error);
    } finally {
      setLoading(false);
    }
  }, [user]);

  useEffect(() => { fetchData(); }, [fetchData]);

  // ... Keep your existing CRUD operations (addTask, updateTask, etc.) here ...

  const aggregates = useMemo(() => {
    let income = 0, expense = 0;
    data.transactions.forEach(t => {
      const amt = convertAmount(t.amount, t.currency, displayCurrency);
      if (t.type === 'income') income += amt; else expense += amt;
    });
    return { income, expense, net: income - expense };
  }, [data.transactions, displayCurrency]);

  return {
    data, loading, displayCurrency, setDisplayCurrency, theme, setTheme,
    // addTask, updateTask, deleteTask, // Ensure these are returned
    aggregates, fetchData
  };
};