import { useState, useEffect, useCallback, useMemo } from 'react';
import { supabase } from '../lib/supabase';
import { convertAmount } from '../lib/currency';
import { useAuth } from '../context/AuthContext';

export const useCashTrack = () => {
  const { user } = useAuth();
  const [data, setData] = useState({
    clients: [], profiles: [], tasks: [], invoices: [], transactions: [], payouts: []
  });
  const [loading, setLoading] = useState(true);
  const [displayCurrency, setDisplayCurrency] = useState('USD');
  const [theme, setTheme] = useState(() => localStorage.getItem('cashtrack_theme') || 'dark');

  useEffect(() => {
    const root = window.document.documentElement;
    root.classList.remove('light', 'dark', 'midnight', 'ocean');
    root.classList.add(theme);
    localStorage.setItem('cashtrack_theme', theme);
  }, [theme]);

  const fetchData = useCallback(async () => {
    if (!user) { setLoading(false); return; }
    setLoading(true);
    
    try {
      const [
        { data: clients }, { data: profiles }, { data: tasks },
        { data: invoices }, { data: transactions }, { data: payouts }
      ] = await Promise.all([
        supabase.from('clients').select('*').order('created_at', { ascending: false }),
        supabase.from('profiles').select('*').order('created_at', { ascending: false }),
        supabase.from('tasks').select('*').order('created_at', { ascending: false }),
        supabase.from('invoices').select('*').order('created_at', { ascending: false }),
        supabase.from('transactions').select('*').order('created_at', { ascending: false }),
        supabase.from('payouts').select('*').order('created_at', { ascending: false })
      ]);

      const normalize = (arr, mapFn) => arr ? arr.map(mapFn) : [];

      setData({
        clients: normalize(clients, c => ({ ...c, avatarColor: c.avatar_color })),
        profiles: normalize(profiles, p => ({ ...p, avatarColor: p.avatar_color })),
        tasks: normalize(tasks, t => ({
          ...t, clientId: t.client_id, assigneeId: t.assignee_id,
          dueDate: t.due_date, completedAt: t.completed_at, createdAt: t.created_at
        })),
        invoices: normalize(invoices, i => ({
          ...i, clientId: i.client_id, createdBy: i.created_by,
          issueDate: i.issue_date, dueDate: i.due_date,
          linkedTaskIds: i.linked_task_ids || []
        })),
        transactions: normalize(transactions, t => ({
          ...t, clientId: t.client_id, assigneeId: t.assignee_id,
          isAutoGenerated: t.is_auto_generated, linkedInvoiceId: t.linked_invoice_id,
          createdAt: t.created_at
        })),
        payouts: normalize(payouts, p => ({
          ...p, memberId: p.member_id, taskId: p.task_id,
          invoiceId: p.invoice_id, invoiceNumber: p.invoice_number,
          createdAt: p.created_at
        }))
      });
    } catch (error) {
      console.error('Data fetch error:', error);
    } finally {
      setLoading(false);
    }
  }, [user]);

  useEffect(() => { fetchData(); }, [fetchData]);

  // --- CRUD OPERATIONS ---
  const addClient = async (client) => {
    const { error } = await supabase.from('clients').insert([{
      id: `c${Date.now()}`, name: client.name, company: client.company,
      email: client.email, avatar_color: client.avatarColor
    }]);
    if (!error) await fetchData();
  };

  const updateClient = async (id, patch) => {
    const { error } = await supabase.from('clients').update({
      name: patch.name, company: patch.company, email: patch.email, avatar_color: patch.avatarColor
    }).eq('id', id);
    if (!error) await fetchData();
  };

  const deleteClient = async (id) => {
    await supabase.from('clients').delete().eq('id', id);
    await fetchData();
  };

  const addTeamMember = async (member) => {
    const result = await supabase.auth.signUp({
      email: member.email, password: member.password,
      options: { data: { name: member.name, role: member.role, avatar_color: member.avatarColor, password: member.password } }
    });
    if (result.error) throw result.error;
    await fetchData();
    return { success: true, creds: { email: member.email, password: member.password } };
  };

  const updateTeamMember = async (id, patch) => {
    const { error } = await supabase.from('profiles').update({
      name: patch.name, role: patch.role, email: patch.email, avatar_color: patch.avatarColor
    }).eq('id', id);
    if (!error) await fetchData();
  };

  const deleteTeamMember = async (id) => {
    await supabase.from('profiles').delete().eq('id', id);
    await fetchData();
  };

  const addTask = async (task) => {
    const { error } = await supabase.from('tasks').insert([{
      id: `t${Date.now()}`, title: task.title, description: task.description,
      status: task.status || 'pending', priority: task.priority || 'medium',
      tags: task.tags?.join(','), due_date: task.dueDate,
      compensation: task.compensation, currency: task.currency,
      client_id: task.clientId, assignee_id: task.assigneeId
    }]);
    if (!error) await fetchData();
  };

  const updateTask = async (id, patch) => {
    const { error } = await supabase.from('tasks').update({
      title: patch.title, description: patch.description, status: patch.status,
      priority: patch.priority, tags: patch.tags?.join(','),
      due_date: patch.dueDate, compensation: patch.compensation, currency: patch.currency,
      client_id: patch.clientId, assignee_id: patch.assigneeId,
      completed_at: patch.status === 'completed' ? new Date().toISOString() : null
    }).eq('id', id);
    if (!error) await fetchData();
  };

  const deleteTask = async (id) => {
    await supabase.from('tasks').delete().eq('id', id);
    await fetchData();
  };

  const addInvoice = async (invoice) => {
    const newInvoice = {
      id: `inv${Date.now()}`, invoice_number: invoice.invoiceNumber,
      client_id: invoice.clientId, created_by: invoice.createdBy,
      status: invoice.status || 'draft', total: invoice.total,
      currency: invoice.currency, items: invoice.items,
      issue_date: invoice.issueDate, due_date: invoice.dueDate,
      linked_task_ids: invoice.linkedTaskIds
    };
    const { error } = await supabase.from('invoices').insert([newInvoice]);
    if (!error) await fetchData();
    return newInvoice;
  };

  const updateInvoice = async (id, patch) => {
    const { error } = await supabase.from('invoices').update({
      status: patch.status, total: patch.total, items: patch.items, due_date: patch.dueDate
    }).eq('id', id);
    if (!error) await fetchData();
  };

  const deleteInvoice = async (id) => {
    await supabase.from('invoices').delete().eq('id', id);
    await fetchData();
  };

  const markInvoiceAsPaid = async (invoiceId) => {
    const { data: inv } = await supabase.from('invoices').select('*').eq('id', invoiceId).single();
    if (!inv) return;

    await supabase.from('invoices').update({ status: 'paid' }).eq('id', invoiceId);

    await supabase.from('transactions').insert([{
      id: `tx${Date.now()}`, type: 'income', amount: inv.total, currency: inv.currency,
      client_id: inv.client_id, assignee_id: inv.created_by,
      category: 'Client Payment', date: new Date().toISOString().split('T')[0],
      description: `Payment for Invoice ${inv.invoice_number}`,
      status: 'paid', is_auto_generated: true, linked_invoice_id: invoiceId
    }]);

    if (inv.linked_task_ids && inv.linked_task_ids.length > 0) {
      const { data: tasks } = await supabase.from('tasks')
        .select('id, assignee_id, compensation, currency, title')
        .in('id', inv.linked_task_ids);
      
      if (tasks) {
        for (const task of tasks) {
          if (task.assignee_id) {
            await supabase.from('payouts').insert([{
              id: `po${Date.now()}${Math.random().toString(36).substr(2, 9)}`,
              member_id: task.assignee_id, amount: task.compensation,
              currency: task.currency, task_id: task.id, task_title: task.title,
              invoice_id: invoiceId, invoice_number: inv.invoice_number,
              date: new Date().toISOString().split('T')[0], status: 'paid'
            }]);
          }
        }
      }
    }
    await fetchData();
  };

  const generateInvoiceFromTasks = async (taskIds, clientId) => {
    const { data: tasks } = await supabase.from('tasks').select('*').in('id', taskIds);
    if (!tasks || tasks.length === 0) return null;

    const total = tasks.reduce((sum, t) => sum + (parseFloat(t.compensation) || 0), 0);
    const items = tasks.map(t => ({ description: t.title, amount: parseFloat(t.compensation) || 0, taskId: t.id }));

    const invoice = {
      invoiceNumber: `INV-${Date.now().toString().slice(-6)}`,
      clientId, createdBy: user?.id, status: 'draft', total, currency: 'USD',
      items, issueDate: new Date().toISOString().split('T')[0],
      dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      linkedTaskIds: taskIds
    };
    return await addInvoice(invoice);
  };

  // ✅ FIXED: These functions were missing from the return statement
  const addManualIncome = async (transaction) => {
    await supabase.from('transactions').insert([{
      id: `tx${Date.now()}`, type: 'income', amount: parseFloat(transaction.amount),
      currency: transaction.currency, client_id: transaction.clientId,
      assignee_id: transaction.assigneeId, category: transaction.category,
      date: transaction.date, description: transaction.description,
      status: 'paid', is_auto_generated: false
    }]);
    await fetchData();
  };

  const addExpense = async (expense) => {
    await supabase.from('transactions').insert([{
      id: `tx${Date.now()}`, type: 'expense', amount: parseFloat(expense.amount),
      currency: expense.currency, category: expense.category,
      date: expense.date, description: expense.description,
      status: 'paid', is_auto_generated: false
    }]);
    await fetchData();
  };

  const toDisplay = useCallback((amount, originalCurrency) =>
    convertAmount(amount || 0, originalCurrency || 'USD', displayCurrency),
    [displayCurrency]
  );

  const aggregates = useMemo(() => {
    const now = new Date();
    const thisMonthStart = new Date(now.getFullYear(), now.getMonth(), 1);
    let income = 0, expense = 0;
    data.transactions.forEach(t => {
      const d = new Date(t.date || t.createdAt || Date.now());
      const displayAmt = toDisplay(t.amount || 0, t.currency);
      if (d >= thisMonthStart) {
        if (t.type === 'income') income += displayAmt; else expense += displayAmt;
      }
    });
    return { income, expense, net: income - expense };
  }, [data.transactions, toDisplay]);

  const memberEarnings = useMemo(() => {
    if (!user) return { total: 0, completedTasks: 0, pendingTasks: 0, taskBreakdown: [], payouts: [] };
    const myTasks = data.tasks.filter(t => t.assigneeId === user.id);
    const completedTasks = myTasks.filter(t => t.status === 'completed');
    const totalEarnings = completedTasks.reduce((sum, t) => sum + toDisplay(parseFloat(t.compensation) || 0, t.currency), 0);
    const taskBreakdown = completedTasks.map(t => ({
      ...t, earnings: toDisplay(parseFloat(t.compensation) || 0, t.currency),
      client: data.clients.find(c => c.id === t.clientId)
    }));
    const myPayouts = data.payouts.filter(p => p.memberId === user.id);
    return {
      total: totalEarnings, completedTasks: completedTasks.length,
      pendingTasks: myTasks.filter(t => t.status !== 'completed').length,
      taskBreakdown, payouts: myPayouts
    };
  }, [data.tasks, data.clients, data.payouts, user, toDisplay]);

  // ✅ FIXED: All functions are now properly returned
  return {
    data, loading, displayCurrency, setDisplayCurrency, theme, setTheme,
    addClient, updateClient, deleteClient,
    addTeamMember, updateTeamMember, deleteTeamMember,
    addTask, updateTask, deleteTask,
    addInvoice, updateInvoice, deleteInvoice,
    markInvoiceAsPaid, generateInvoiceFromTasks,
    addManualIncome, addExpense, // ✅ These were missing!
    toDisplay, aggregates, memberEarnings, fetchData
  };
};