import { useState, useEffect, useCallback, useMemo } from 'react';
import { convertAmount } from '../lib/currency';

const API_URL = 'http://localhost/cashtrack-api/api.php';

export const useCashTrack = (user) => {
  const [data, setData] = useState({
    clients: [], profiles: [], tasks: [], invoices: [], transactions: [], payouts: []
  });
  const [loading, setLoading] = useState(true);
  const [displayCurrency, setDisplayCurrency] = useState('PKR');
  const [theme, setTheme] = useState(() => localStorage.getItem('cashtrack_theme') || 'dark');

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const response = await fetch(`${API_URL}?action=get_all`);
      const result = await response.json();
      
      if (result.success && result.data) {
        const formatted = {
          clients: result.data.clients.map(c => ({ ...c, avatarColor: c.avatar_color })),
          profiles: result.data.profiles.map(p => ({ ...p, avatarColor: p.avatar_color })),
          tasks: result.data.tasks.map(t => ({ ...t, clientId: t.client_id, assigneeId: t.assignee_id, dueDate: t.due_date, completedAt: t.completed_at, createdAt: t.created_at })),
          invoices: result.data.invoices.map(i => ({ ...i, clientId: i.client_id, createdBy: i.created_by, issueDate: i.issue_date, dueDate: i.due_date, linkedTaskIds: i.linked_task_ids ? JSON.parse(i.linked_task_ids) : [] })),
          transactions: result.data.transactions.map(t => ({ ...t, clientId: t.client_id, assigneeId: t.assignee_id, isAutoGenerated: t.is_auto_generated == 1, linkedInvoiceId: t.linked_invoice_id, createdAt: t.created_at })),
          payouts: result.data.payouts.map(p => ({ ...p, memberId: p.member_id, taskId: p.task_id, invoiceId: p.invoice_id, invoiceNumber: p.invoice_number, createdAt: p.created_at }))
        };
        setData(formatted);
      }
    } catch (error) {
      console.error('Fetch Error:', error);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchData(); }, [fetchData]);
  useEffect(() => {
    document.documentElement.className = theme;
    localStorage.setItem('cashtrack_theme', theme);
  }, [theme]);

  const callApi = async (action, payload) => {
    try {
      const response = await fetch(API_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action, ...payload })
      });
      const result = await response.json();
      if (!result.success) {
        throw new Error(result.error || 'API call failed');
      }
      return result;
    } catch (error) {
      console.error('API Call Error:', error);
      throw error;
    }
  };

  // --- CLIENTS ---
  const addClient = async (c) => {
    const newClient = { ...c, id: `c${Date.now()}`, createdAt: new Date().toISOString() };
    await callApi('add_client', { client: { ...newClient, avatar_color: newClient.avatarColor } });
    setData(prev => ({ ...prev, clients: [newClient, ...prev.clients] }));
  };

  const updateClient = async (id, patch) => {
    await callApi('update_client', { client: { id, ...patch, avatar_color: patch.avatarColor } });
    setData(prev => ({ ...prev, clients: prev.clients.map(c => c.id === id ? { ...c, ...patch } : c) }));
  };

  const deleteClient = async (id) => {
    await callApi('delete_client', { id });
    setData(prev => ({ ...prev, clients: prev.clients.filter(c => c.id !== id) }));
  };

  // --- TEAM MEMBERS ---
  const addTeamMember = async (m) => {
    const newMember = { ...m, id: `p${Date.now()}`, createdAt: new Date().toISOString() };
    await callApi('add_profile', { profile: { ...newMember, avatar_color: newMember.avatarColor, password: m.password } });
    setData(prev => ({ ...prev, profiles: [...prev.profiles, newMember] }));
    return { success: true, creds: { email: m.email, password: m.password } };
  };

  const updateTeamMember = async (id, patch) => {
    await callApi('update_profile', { profile: { id, ...patch, avatar_color: patch.avatarColor } });
    setData(prev => ({ ...prev, profiles: prev.profiles.map(m => m.id === id ? { ...m, ...patch } : m) }));
  };

  const deleteTeamMember = async (id) => {
    await callApi('delete_profile', { id });
    setData(prev => ({ ...prev, profiles: prev.profiles.filter(m => m.id !== id) }));
  };

  // --- TASKS ---
  const addTask = async (t) => {
    const newTask = { ...t, id: `t${Date.now()}`, createdAt: new Date().toISOString(), priority: t.priority || 'medium', tags: t.tags || [] };
    await callApi('add_task', { task: { ...newTask, due_date: newTask.dueDate, client_id: newTask.clientId, assignee_id: newTask.assigneeId } });
    setData(prev => ({ ...prev, tasks: [newTask, ...prev.tasks] }));
  };

  const updateTask = async (id, patch) => {
    const currentTask = data.tasks.find(t => t.id === id);
    const completedAt = patch.status === 'completed' && currentTask?.status !== 'completed' ? new Date().toISOString() : currentTask?.completedAt;
    
    await callApi('update_task', { task: { id, ...patch, due_date: patch.dueDate, client_id: patch.clientId, assignee_id: patch.assigneeId, completed_at: completedAt } });
    setData(prev => ({ ...prev, tasks: prev.tasks.map(t => t.id === id ? { ...t, ...patch, completedAt } : t) }));
  };

  const deleteTask = async (id) => {
    await callApi('delete_task', { id });
    setData(prev => ({ ...prev, tasks: prev.tasks.filter(t => t.id !== id) }));
  };

  // --- INVOICES ---
  const addInvoice = async (inv) => {
    const newInv = { ...inv, id: `inv${Date.now()}`, createdAt: new Date().toISOString() };
    await callApi('add_invoice', { 
      invoice: { 
        id: newInv.id,
        invoiceNumber: newInv.invoiceNumber,
        clientId: newInv.clientId,
        createdBy: newInv.createdBy,
        status: newInv.status,
        total: newInv.total,
        currency: newInv.currency,
        items: newInv.items,
        issueDate: newInv.issueDate,
        dueDate: newInv.dueDate,
        linkedTaskIds: newInv.linkedTaskIds
      } 
    });
    setData(prev => ({ ...prev, invoices: [newInv, ...prev.invoices] }));
    return newInv;
  };

  const updateInvoice = async (id, patch) => {
    await callApi('update_invoice', { invoice: { id, ...patch, due_date: patch.dueDate } });
    setData(prev => ({ ...prev, invoices: prev.invoices.map(i => i.id === id ? { ...i, ...patch } : i) }));
  };

  const deleteInvoice = async (id) => {
    await callApi('delete_invoice', { id });
    setData(prev => ({ ...prev, invoices: prev.invoices.filter(i => i.id !== id) }));
  };

  const markInvoiceAsPaid = async (invoiceId) => {
    await callApi('mark_invoice_paid', { invoiceId });
    await fetchData();
  };

  // ✅ FIXED: Now properly async and returns the invoice
  const generateInvoiceFromTasks = async (taskIds, clientId) => {
    const completedTasks = (data.tasks || []).filter(t => taskIds.includes(t.id) && t.status === 'completed');
    if (completedTasks.length === 0) return null;

    const total = completedTasks.reduce((sum, t) => sum + (parseFloat(t.compensation) || 0), 0);
    const items = completedTasks.map(t => ({
      description: t.title,
      amount: parseFloat(t.compensation) || 0,
      taskId: t.id
    }));

    const invoice = {
      invoiceNumber: `INV-${Date.now().toString().slice(-6)}`,
      clientId,
      createdBy: user?.id,
      status: 'draft',
      total,
      currency: 'USD',
      items,
      issueDate: new Date().toISOString().split('T')[0],
      dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      linkedTaskIds: taskIds
    };

    // ✅ FIXED: Now awaiting the API call and returning the result
    const newInv = await addInvoice(invoice);
    return newInv;
  };

  // --- TRANSACTIONS ---
  const addManualIncome = async (t) => {
    await callApi('add_manual_income', { transaction: { amount: t.amount, currency: t.currency, clientId: t.clientId, assigneeId: t.assigneeId, category: t.category, date: t.date, description: t.description } });
    await fetchData();
  };

  const addExpense = async (e) => {
    await callApi('add_expense', { expense: { amount: e.amount, currency: e.currency, category: e.category, date: e.date, description: e.description } });
    await fetchData();
  };

  // --- DATA PROCESSING ---
  const toDisplay = useCallback((amount, originalCurrency) => convertAmount(amount || 0, originalCurrency || 'USD', displayCurrency), [displayCurrency]);

  const aggregates = useMemo(() => {
    const now = new Date();
    const thisMonthStart = new Date(now.getFullYear(), now.getMonth(), 1);
    let income = 0, expense = 0;
    (data.transactions || []).forEach((t) => {
      const d = new Date(t.date || t.createdAt || Date.now());
      const displayAmt = toDisplay(t.amount || 0, t.currency);
      if (d >= thisMonthStart) {
        if (t.type === 'income') income += displayAmt; else expense += displayAmt;
      }
    });
    return { income, expense, net: income - expense };
  }, [data.transactions, toDisplay]);

  const memberEarnings = useMemo(() => {
    if (!user) return { total: 0, completedTasks: 0, pendingTasks: 0, taskBreakdown: [], payouts: [] };
    const myTasks = (data.tasks || []).filter(t => t.assigneeId === user.id);
    const completedTasks = myTasks.filter(t => t.status === 'completed');
    const totalEarnings = completedTasks.reduce((sum, t) => sum + toDisplay(parseFloat(t.compensation) || 0, t.currency), 0);
    const taskBreakdown = completedTasks.map(t => ({ ...t, earnings: toDisplay(parseFloat(t.compensation) || 0, t.currency), client: (data.clients || []).find(c => c.id === t.clientId) }));
    const myPayouts = (data.payouts || []).filter(p => p.memberId === user.id);
    return { total: totalEarnings, completedTasks: completedTasks.length, pendingTasks: myTasks.filter(t => t.status !== 'completed').length, taskBreakdown, payouts: myPayouts };
  }, [data.tasks, data.clients, data.payouts, user, toDisplay]);

  return { 
    data, setData, loading, displayCurrency, setDisplayCurrency, theme, setTheme,
    addClient, updateClient, deleteClient, addTeamMember, updateTeamMember, deleteTeamMember,
    addTask, updateTask, deleteTask, addInvoice, updateInvoice, deleteInvoice, markInvoiceAsPaid,
    generateInvoiceFromTasks, addManualIncome, addExpense, toDisplay, aggregates, memberEarnings
  };
};